---
ansible_connection: local

openshift_cluster_content:
- object: dev-stage
  content:
  - name: sqlserver
    template: "{{ playbook_dir }}/templates/coolstore/deploy-sqlserver-secret.yml"
    params: "{{ playbook_dir }}/params/coolstore/deploy-sqlserver"
    namespace: "{{ test_namespace }}"
    tags:
    - coolstore-deploy
  - name: sqlserver
    template: "{{ playbook_dir }}/templates/coolstore/deploy-sqlserver.yml"
    params: "{{ playbook_dir }}/params/coolstore/deploy-sqlserver"
    namespace: "{{ test_namespace }}"
    tags:
    - coolstore-deploy
  - name: coolstore
    template: "{{ playbook_dir }}/templates/coolstore/deploy-coolstore.yml"
    params: "{{ playbook_dir }}/params/coolstore/deploy-dev"
    namespace: "{{ dev_namespace }}"
    tags:
    - coolstore-deploy
- object: test-stage
  content:
  - name: sqlserver
    template: "{{ playbook_dir }}/templates/coolstore/deploy-sqlserver-secret.yml"
    params: "{{ playbook_dir }}/params/coolstore/deploy-sqlserver"
    namespace: "{{ test_namespace }}"
    tags:
    - coolstore-deploy
  - name: sqlserver
    template: "{{ playbook_dir }}/templates/coolstore/deploy-sqlserver.yml"
    params: "{{ playbook_dir }}/params/coolstore/deploy-sqlserver"
    namespace: "{{ test_namespace }}"
    tags:
    - coolstore-deploy
  - name: coolstore
    template: "{{ playbook_dir }}/templates/coolstore/deploy-coolstore.yml"
    params: "{{ playbook_dir }}/params/coolstore/deploy-test"
    namespace: "{{ test_namespace }}"
    tags:
    - coolstore-deploy