---
ansible_connection: local

openshift_cluster_content:
- object: app-builds
  content:
  - name: coolstore-app-build
    template: "{{ playbook_dir }}/templates/coolstore/build.yml"
    params: "{{ playbook_dir }}/params/coolstore/build"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - coolstore-build
  - name: coolstore-app-pipeline
    template: "{{ playbook_dir }}/templates/coolstore/pipeline.yml"
    params: "{{ playbook_dir }}/params/coolstore/pipeline"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - coolstore-build
- object: prod-stage
  content:
  - name: sqlserver
    template: "{{ playbook_dir }}/templates/coolstore/deploy-sqlserver-secret.yml"
    params: "{{ playbook_dir }}/params/coolstore/deploy-prod"
    namespace: "{{ prod_namespace }}"
    tags:
    - coolstore-deploy
  - name: coolstore
    template: "{{ playbook_dir }}/templates/coolstore/deploy-coolstore-prod.yml"
    params: "{{ playbook_dir }}/params/coolstore/deploy-prod"
    namespace: "{{ prod_namespace }}"
    tags:
    - coolstore-deploy
  - name: jenkins-edit-rolebinding
    template: "{{ playbook_dir }}/templates/rolebinding/jenkins-edit.yml"
    params: "{{ playbook_dir }}/params/coolstore/role-jenkins"
    namespace: "{{ prod_namespace }}"
    tags:
    - coolstore-deploy