kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Application template Coolstore Monolith using Git source build
    iconClass: icon-jboss
    tags: eap,sqlserver,javaee,java,database,jboss,xpaas
    version: 1.0.0
    openshift.io/display-name: Red Hat Forum - Coolstore Monnolith using source build
  name: coolstore-monolith-sqlserver
labels:
  template: coolstore-monolith-sqlserver
message: The resources (build config, imagestreams, etc) for
  building the Coolstore Monolith SQL Server has been created in your project.
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: coolstore
    labels:
      application: coolstore
      build: coolstore
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: coolstore
    labels:
      application: coolstore
  spec:
    source:
      type: Git
      git:
        uri: ${COOLSTORE_GIT_REPOSITORY}
        ref: ${COOLSTORE_GIT_BRANCH}
    strategy:
      type: Source
      sourceStrategy:
        env:
        - name: CUSTOM_INSTALL_DIRECTORIES
          value: /install
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: jboss-eap71-openshift:1.1
    output:
      to:
        kind: ImageStreamTag
        namespace: ""
        name: coolstore:latest
    triggers:
    - type: ImageChange
    - type: ConfigChange
parameters:
- displayName: Git Repository for coolstore
  name: COOLSTORE_GIT_REPOSITORY
  value: https://github.com/demo-redhat-forum-2018/monolith.git
  required: true
- displayName: Git branch for coolstore
  name: COOLSTORE_GIT_BRANCH
  value: sqlserver
  required: true