kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Application template Coolstore Monolith using Git source build & SQL Server
    iconClass: icon-jboss
    tags: eap,sqlserver,javaee,java,database,jboss,xpaas
    version: 1.0.0
    openshift.io/display-name: Red Hat Demos - Coolstore Monnolith using source build
  name: coolstore-monolith-sqlserver
labels:
  template: coolstore-monolith-sqlserver
message: The resources (build config, deploy config, service, imagestreams, etc) for
  running the Coolstore Monolith SQL Server demo has been created in your project.
objects:
- apiVersion: v1
  stringData:
    database-name: "${SQLSERVER_DATABASE_NAME}"
    database-password: "${SQLSERVER_PASSWORD}"
    database-user: "sa"
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-database_name: '{.data[''database-name'']}'
      template.openshift.io/expose-password: '{.data[''database-password'']}'
      template.openshift.io/expose-username: '{.data[''database-user'']}'
    labels:
      app: coolstore
    name: coolstore-sqlserver
  type: Opaque
parameters:
- displayName: ImageStream Namespace
  description: Namespace in which the ImageStreams for Red Hat Middleware images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you've installed the ImageStreams in a
    different namespace/project.
  name: IMAGE_STREAM_NAMESPACE
  value: openshift
  required: true
- displayName: SQL Server Service Name
  name: SQLSERVER_SERVICE_NAME
  value: sqlserver
  required: true
- displayName: SQL Server SA Password
  name: SQLSERVER_PASSWORD
  from: '[#-$]{1}[a-zA-Z]{10}[0-9]{2}'
  generate: expression
  required: true
- displayName: SQL Server Database Name
  name: SQLSERVER_DATABASE_NAME
  value: monolith
  required: true
- displayName: SQL Server Port
  name: SQLSERVER_PORT
  value: "1433"
  required: true
- displayName: Coolstore image tag to use 
  name: APP_TAG
  value: latest
  required: true
- displayName: Coolstore imageStream 
  name: IMAGE_NAMESPACE
  value: mono-ci-cd
  required: true