kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Application template Coolstore Monolith using Git source build & SQL Server
    iconClass: icon-jboss
    tags: eap,sqlserver,javaee,java,database,jboss,xpaas
    version: 1.0.0
    openshift.io/display-name: Red Hat Demos - Coolstore Monnolith using source build
  name: coolstore-monolith-sqlserver
labels:
  template: coolstore-monolith-sqlserver
message: The resources (build config, deploy config, service, imagestreams, etc) for
  running the Coolstore Monolith SQL Server demo has been created in your project.
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-password: '{.data[''database-password'']}'
      template.openshift.io/expose-username: '{.data[''database-user'']}'
    name: '${DATABASE_SERVICE_NAME}'
  stringData:
    database-password: '${SQLSERVER_PASSWORD}'
    database-user: 'sa'
parameters:
  - description: The name assigned to the database service.
    displayName: Database Service Name
    name: DATABASE_SERVICE_NAME
    required: true
    value: sqlserver
  - description: The name of a database to create within SQLServer.
    displayName: Database Name
    name: DATABASE_NAME
    required: true
    value: monolith
  - description: Database persistent volume size
    displayName: Database volume size
    name: DATABASE_SIZE
    required: false
    value: 10Gi
  - description: The name of the image to use
    displayName: Container Image name
    name: IMAGE_NAME
    required: true
    value: sqlserver
  - description: The namespace where to get container image
    displayName: Container Image name
    name: IMAGE_NAMESPACE
    required: true
    value: openshift
  - description: SQL Server password to authenticate using sa user.
    displayName: SQL Server sa user password
    from: '[a-zA-Z0-9]{16}'
    generate: expression
    name: SQLSERVER_PASSWORD
  - displayName: Coolstore image tag to use 
    name: APP_TAG
    value: latest
    required: true