
kind: Template
apiVersion: v1
metadata:
  annotations:
    description: Application template Coolstore Monolith using Git source build & SQL Server
    iconClass: icon-jboss
    tags: eap,sqlserver,javaee,java,database,jboss,xpaas
    version: 1.0.0
    openshift.io/display-name: Red Hat Demos - Coolstore Monnolith using source build
  name: coolstore-monolith-sqlserver
labels:
  template: coolstore-monolith-sqlserver
message: The resources (build config, deploy config, service, imagestreams, etc) for
  running the Coolstore Monolith SQL Server demo has been created in your project.
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-password: '{.data[''database-password'']}'
      template.openshift.io/expose-username: '{.data[''database-user'']}'
    name: '${DATABASE_SERVICE_NAME}'
  stringData:
    database-password: '${SQLSERVER_PASSWORD}'
    database-user: 'sa'
parameters:
  - description: The name assigned to the database service.
    displayName: Database Service Name
    name: DATABASE_SERVICE_NAME
    required: true
    value: sqlserver
  - description: SQL Server password to authenticate using sa user.
    displayName: SQL Server sa user password
    from: '[a-zA-Z0-9]{16}'
    generate: expression
    name: SQLSERVER_PASSWORD