apiVersion: v1
kind: Template
labels:
  template: openshift-tasks
message: See https://github.com/nmasse-itix/openshift-tasks for more details.
metadata:
  annotations:
    description: |-
      A demo application that exhibits the main features of OpenShift. It is written
      in Java for JBoss EAP 7 and features a CI/CD environment with Blue/Green deployment.
    openshift.io/display-name: OpenShift Tasks
    tags: instant-app,jboss,jenkins
    template.openshift.io/documentation-url: https://github.com/nmasse-itix/openshift-tasks
    template.openshift.io/long-description: A demo using Java for JBoss EAP 7 and Jenkins, running on OpenShift
    template.openshift.io/provider-display-name: Nicolas Massé
    template.openshift.io/support-url: https://github.com/nmasse-itix/openshift-tasks/issues
  name: openshift-tasks
objects:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "coolstore-monolith-tasks-pipeline"
    namespace: ${BUILD_PROJECT}
    labels:
      template: coolstore-monolith
  spec:
    source:
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_BRANCH}
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: ${JENKINSFILE_PATH}
        env:
          - name: OPENSHIFT_IMAGE_STREAM
            value: coolstore
          - name: OPENSHIFT_BUILD_CONFIG
            value: coolstore
          - name: OPENSHIFT_SERVICE
            value: coolstore
          - name: OPENSHIFT_DEPLOYMENT_CONFIG
            value: coolstore
          - name: OPENSHIFT_BUILD_PROJECT
            value: ${BUILD_PROJECT}
          - name: OPENSHIFT_TEST_ENVIRONMENT
            value: ${TEST_PROJECT}
          - name: OPENSHIFT_PROD_ENVIRONMENT
            value: ${PROD_PROJECT}
          - name: OPENSHIFT_TEST_URL
            value: http://${TEST_ROUTE_HOSTNAME}
          - name: NEXUS_REPO_URL
            value: ${NEXUS_REPO_URL}
          - name: NEXUS_MIRROR_URL
            value: ${NEXUS_MIRROR_URL}
          - name: NEXUS_USER
            value: ${NEXUS_USER}
          - name: NEXUS_PASSWORD
            value: ${NEXUS_PASSWORD}
          - name: OVH_URL
            value: ${OVH_URL}
          - name: OVH_TOKEN
            value: ${OVH_TOKEN}
          - name: AZURE_URL
            value: ${AZURE_URL}
          - name: AZURE_TOKEN
            value: ${AZURE_TOKEN}
          - name: QUAY_REGISTRY
            value: ${QUAY_REGISTRY}
          - name: QUAY_USER
            value: ${QUAY_USER}
          - name: QUAY_PASSWORD
            value: ${QUAY_PASSWORD}
    triggers:
    - github:
        secret: secret101
      type: GitHub
    - generic:
        secret: secret101
      type: Generic
parameters:
- description: The name of the OpenShift Project to that holds the dev environment.
  displayName: Development Environment
  name: DEV_PROJECT
  value: mono-dev
- description: The name of the OpenShift Project to that holds the build environment.
  displayName: Build Environment
  name: BUILD_PROJECT
  value: mono-ci-cd
- description: The name of the OpenShift Project to that holds the test environment.
  displayName: Test Environment
  name: TEST_PROJECT
  value: mono-test
- description: The name of the OpenShift Project to that holds the prod environment.
  displayName: Production Environment
  name: PROD_PROJECT
  value: mono-prod
- description: The GIT repository to use.
  displayName: GIT Repo URL
  name: GIT_REPO
  value:  https://github.com/demo-redhat-forum-2018/monolith.git
- description: The GIT branch to use.
  displayName: GIT Branch
  name: GIT_BRANCH
  value:  master
- description: Path to the Jenkinsfile to use.
  displayName: Jenkinsfile Path
  name: JENKINSFILE_PATH
  value:  Jenkinsfile
- description: The Nexus repository that will store the software binaries
  displayName: Nexus Repo URL
  name: NEXUS_REPO_URL
  value: http://gitux01.openhybridcloud.io:8081/repository/coolstore-monolith/
- description: The Nexus Repository URL for maven mirroring
  displayName: Nexus Mirror URL
  name: NEXUS_MIRROR_URL
  value: http://gitux01.openhybridcloud.io:8081/repository/maven-public/
- description: The Nexus User used to push the software to Nexus
  displayName: Nexus Username
  name: NEXUS_USER
  value: admin
- description: The password of the Nexus User used to push the software to Nexus
  displayName: Nexus Password
  name: NEXUS_PASSWORD
  value: admin123
- displayName: OVH URL
  name: OVH_URL
  value: https://openshift.openhybridcloud.io:8443
- displayName: OVH Token
  name: OVH_TOKEN
  value: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJoeWJyaWQtY2ktY2QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiamVua2lucy10b2tlbi1kcXQyaiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJqZW5raW5zIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYTgwNTA2YjYtYzdkMi0xMWU4LThhOTItMDAxYTRhMTYwMTk0Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omh5YnJpZC1jaS1jZDpqZW5raW5zIn0.rlZlp_2xHknQV0yJMyiokCM_5wgjP4b6nhfOYrs2ifAcTxD7lJ01tTDp6EDbtmoBWTPTnGav86woNh1i-tp7CgVUT-4fQO9LbUY8fZp9pbO2_f354FkDKcvsKqmjyw79ckljrj1qDMMlZtTZ6vFU48rEqHeaIOwvFZdSX82xikrS2rguKg0AAihAUPtFuqnAo4Xdhv7QRGlDXJFJgygfHg3T-u5QmovFfKpp7GMYoUPdU2MjW-BrMFbh1DbMNAszYmD-sAurRCT02NyslWeNqcioW4mTERRjfQNEI0tfKBjssdi_zmgSIhZlYJn1etqaIeUmC3dkj0mUweUgN4e4XA
- displayName: Azure URL
  name: AZURE_URL
  value: https://openshift.openhybridcloud.io:8443
- displayName: Azure Token
  name: AZURE_TOKEN
  value: admin1eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJoeWJyaWQtY2ktY2QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiamVua2lucy10b2tlbi1kcXQyaiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJqZW5raW5zIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYTgwNTA2YjYtYzdkMi0xMWU4LThhOTItMDAxYTRhMTYwMTk0Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omh5YnJpZC1jaS1jZDpqZW5raW5zIn0.rlZlp_2xHknQV0yJMyiokCM_5wgjP4b6nhfOYrs2ifAcTxD7lJ01tTDp6EDbtmoBWTPTnGav86woNh1i-tp7CgVUT-4fQO9LbUY8fZp9pbO2_f354FkDKcvsKqmjyw79ckljrj1qDMMlZtTZ6vFU48rEqHeaIOwvFZdSX82xikrS2rguKg0AAihAUPtFuqnAo4Xdhv7QRGlDXJFJgygfHg3T-u5QmovFfKpp7GMYoUPdU2MjW-BrMFbh1DbMNAszYmD-sAurRCT02NyslWeNqcioW4mTERRjfQNEI0tfKBjssdi_zmgSIhZlYJn1etqaIeUmC3dkj0mUweUgN4e4XA23
- displayName: Quay Registry
  name: QUAY_REGISTRY
  value: quay.io/demoforum/coolstore-monolith
- displayName: Quay user
  name: QUAY_USER
  value: demoforum18
- displayName: Quay Password
  name: QUAY_PASSWORD
  value: "#redhat123"