---
kind: Template
apiVersion: v1
metadata:
  name: image-puller
  annotations:
    openshift.io/display-name: Image puller
    description: Image puller in source project
    iconClass: icon-cube
    tags: cube
objects:
- apiVersion: v1
  kind: RoleBinding
  groupNames:
  - system:serviceaccounts:${NAMESPACE}
  metadata:
    name: image-puller-${NAMESPACE}
  roleRef:
    name: "system:image-puller"
  subjects:
  - kind: SystemGroup
    name: system:serviceaccounts:${NAMESPACE}
  userNames: 
parameters:
- name: NAMESPACE
  displayName: Project/Namespace for the App
  description: The project/namespace where the App is deployed.
  required: true
labels:
  template: image-puller-role-bindings-template