---
kind: Template
apiVersion: v1
metadata:
  name: jenkins-edit
  annotations:
    openshift.io/display-name: Jenkins Edit
    description: Edit role for Jenkins Service Account
    iconClass: icon-jenkins
objects:
- apiVersion: v1
  kind: RoleBinding
  groupNames: null
  metadata:
    name: jenkins-edit
  roleRef:
    name: "edit"
  subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: ${NAMESPACE}
  userNames:
  - system:serviceaccount:${NAMESPACE}:jenkins
parameters:
- name: NAMESPACE
  displayName: Project/Namespace for the App
  description: The project/namespace where the App is deployed.
  required: true
labels:
  template: jenkins-edit-role-bindings-template